root: true

env:
  browser: true
  commonjs: true
  node: true
  shared-node-browser: true
  es6: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest

# Rules below use settings that differ from or are not included in eslint:recommended
rules:

  # Logical Rules
  no-alert:
    - error
  no-array-constructor:
    - error
  no-bitwise:
    - error
  no-caller:
    - error
  no-confusing-arrow:
    - error
  no-console:
    - off
  no-else-return:
    - error
    - allowElseIf: false
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-label:
    - error
  no-fallthrough:
    - error
  no-floating-decimal:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-label-var:
    - error
  no-labels:
    - error
  no-lonely-if:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - error
    - ignore: [-1, 0, 1, 2]
      enforceConst: true
      detectObjects: true
  no-mixed-operators:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multi-assign:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-multiple-empty-lines:
    - error
  no-negated-condition:
    - error
  no-nested-ternary:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-object:
    - error
  no-new-wrappers:
    - error
  no-param-reassign:
    - error
  no-proto:
    - error
  no-return-assign:
    - error
    - always
  no-script-url:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
    - allowInParentheses: false
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
  no-tabs:
    - error
  no-template-curly-in-string:
    - error
  no-throw-literal:
    - error
  no-trailing-spaces:
    - error
  no-undef-init:
    - error
  no-undefined:
    - error
  no-unneeded-ternary:
    - error
  no-unreachable-loop:
    - error
  no-unused-expressions:
    - error
  no-use-before-define:
    - error
    - nofunc
  no-useless-computed-key:
    - error
    - enforceForClassMembers: true
  no-useless-concat:
    - error
  no-useless-rename:
    - error
  no-useless-return:
    - error
  no-var:
    - error
  no-void:
    - error
  no-warning-comments:
    - error
  no-whitespace-before-property:
    - error

  # Style Rules
  array-bracket-newline:
    - error
    - consistent
  array-element-newline:
    - error
    - consistent
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
  block-scoped-var:
    - error
  block-spacing:
    - error
  brace-style:
    - error
    - allman
    - allowSingleLine: true
  camelcase:
    - error
    - properties: never
  capitalized-comments:
    - error
    - always
  comma-dangle:
    - error
  comma-spacing:
    - error
  comma-style:
    - error
  consistent-return:
    - error
  curly:
    - error
  default-case:
    - error
  default-case-last:
    - error
  default-param-last:
    - error
  dot-notation:
    - error
  eol-last:
    - error
  eqeqeq:
    - error
  func-call-spacing:
    - error
  func-name-matching:
    - error
  func-names:
    - error
    - never
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
  implicit-arrow-linebreak:
    - error
  indent:
    - error
    - 4
    - SwitchCase: 1
  init-declarations:
    - error
  key-spacing:
    - error
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  max-statements-per-line:
    - error
  multiline-ternary:
    - error
    - always-multiline
  new-cap:
    - error
  new-parens:
    - error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 1
  no-extra-parens:
    - error
    - all
    - nestedBinaryExpressions: false
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
  one-var:
    - error
    - var: never
      let: never
      const: never
      separateRequires: true
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment:
    - error
  operator-linebreak:
    - error
    - after
    - overrides:
          "?": before
          ":": before
  padded-blocks:
    - error
    - never
  prefer-const:
    - error
  prefer-promise-reject-errors:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  quote-props:
    - error
    - consistent-as-needed
  quotes:
    - error
    - double
  require-await:
    - error
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  semi-style:
    - error
  sort-imports:
    - error
  sort-keys:
    - error
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
  switch-colon-spacing:
    - error
  strict:
    - error
  template-curly-spacing:
    - error
  unicode-bom:
    - error
  wrap-regex:
    - error
  yoda:
    - error
