maxerr: false
text-ignore-regex: false
raw-ignore-regex: false
attr-name-ignore-regex: false
id-class-ignore-regex: false
line-max-len-ignore-regex: false
rules:
  attr-bans:
    - true
    - align
    - background
    - bgcolor
    - border
    - frameborder
    - longdesc
    - marginwidth
    - marginheight
    - scrolling
    - style
    - width
  attr-name-style: false
  attr-new-line: false
  attr-no-dup: true
  attr-no-unsafe-char: true
  attr-order: false
  attr-quote-style:
    - true
    - double
  attr-req-value: true
  attr-validate: true
  button-req-content: true
  class-no-dup: true
  class-style:
    - true
    - dash
  doctype-first:
    - true
    - smart
  doctype-html5: true
  fig-req-figcaption: true
  focusable-tabindex-style: false
  head-req-title: true
  head-valid-content-model: true
  href-style: false
  html-req-lang: true
  html-valid-content-model: true
  id-class-no-ad: true
  id-class-style: false
  id-no-dup: true
  img-req-alt: true
  img-req-src: false
  indent-style:
    - true
    - spaces
  indent-width: false
  input-radio-req-name: true
  input-req-label: false
  label-req-for: true
  lang-style:
    - true
    - case
  line-end-style:
    - true
    - lf
  line-max-len: false
  line-no-trailing-whitespace: true
  link-req-noopener: true
  spec-char-escape: false
  table-req-caption: false
  table-req-header: true
  tag-bans:
    - true
    - style
    - b
    - i
  tag-close: true
  tag-name-lowercase: true
  tag-name-match: true
  tag-req-attr: false
  tag-self-close: false
  title-max-len:
    - true
    - 60
  title-no-dup: true
