name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Sync Repository to Remote
      uses: up9cloud/action-rsync@v1.3
      env:
        HOST: ${{ secrets.SYNC_SERVER }}
        PORT: ${{ secrets.SYNC_PORT }}
        USER: ${{ secrets.SYNC_USER }}
        KEY:  ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        TARGET: ${{ secrets.SYNC_TARGET_PATH }}
        ARGS_MORE: '--exclude=/node_modules/'
        MODE: push
        RUN_SCRIPT_ON: source

    - name: Remote Install via SSH
      uses: appleboy/ssh-action@v0.1.4
      env:
        path: ${{ secrets.NODE_MODULES_TARGET_PATH }}
      with:
        host: ${{ secrets.SYNC_SERVER }}
        port: ${{ secrets.SYNC_PORT }}
        username: ${{ secrets.SYNC_USER }}
        key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        debug: true
        envs: path
        script: ../bin/npm install --dry-run $path
