name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Sync Repository to Remote
      uses: up9cloud/action-rsync@v1.3
      env:
        HOST: ${{ secrets.SYNC_SERVER }}
        PORT: ${{ secrets.SYNC_PORT }}
        USER: ${{ secrets.SYNC_USER }}
        KEY:  ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        TARGET: ${{ secrets.SYNC_TARGET_PATH }}
        ARGS_MORE: '--exclude=/node_modules/ -vvv'
        SSH_ARGS: '-p ${{ secrets.SYNC_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=debug3'
        MODE: push
        RUN_SCRIPT_ON: source
        VERBOSE: true

    - name: Remote Package Install via SSH
      uses: appleboy/ssh-action@v0.1.4
      env:
        NODE_MODULES_PATH: ${{ secrets.NODE_MODULES_TARGET_PATH }}
        NPM_PATH: ${{ secrets.NPM_TARGET_PATH }}
      with:
        host: ${{ secrets.SYNC_SERVER }}
        port: ${{ secrets.SYNC_PORT }}
        username: ${{ secrets.SYNC_USER }}
        key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        script_stop: true
        envs: NODE_MODULES_PATH, NPM_PATH
        script: $NPM_PATH/npm install $NODE_MODULES_PATH

    - name: Remote Server Restart via SSH
      uses: appleboy/ssh-action@v0.1.4
      env:
        VENV_ACTIVATION_PATH: ${{ secrets.VENV_ACTIVATION_TARGET_PATH }}
        CODE_PATH: ${{ secrets.SYNC_TARGET_PATH }}
        SELECTOR_PATH: ${{ secrets.SELECTOR_TARGET_PATH }}
      with:
        host: ${{ secrets.SYNC_SERVER }}
        port: ${{ secrets.SYNC_PORT }}
        username: ${{ secrets.SYNC_USER }}
        key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        script_stop: true
        envs: VENV_ACTIVATION_PATH, CODE_PATH, SELECTOR_PATH
        script: |
          source $VENV_ACTIVATION_PATH/activate && cd $CODE_PATH
          $SELECTOR_PATH/cloudlinux-selector restart --json --interpreter nodejs --app-root $CODE_PATH
