name: Code Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Lint Repository Files
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.15.0

    - name: Install Projects via NPM
      run: npm ci

    - name: Lint
      run: npm run lint
