name: Code Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-js:
    runs-on: ubuntu-latest
    name: Lint JavaScript Files
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Lint JS
      run: npm run lint:js

  lint-html:
    runs-on: ubuntu-latest
    name: Lint HTML Files
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Lint HTML
      run: npm run lint:html

  lint-vash:
    runs-on: ubuntu-latest
    name: Lint Vash Files
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Lint Vash
      run: npm run lint:vash
