name: Code Formatting Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Prettier Check
        uses: actionsx/prettier@v2
        with:
          # Prettier CLI arguments
          args: --check .
